import { User } from '../types/auth';

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8080';

export interface CaptchaApiResponse {
  token: string;
  captchaToken: string;
  image?: string;
  svg?: string;
  expiresAt: number;
}

export interface RegisterApiPayload {
  username: string;
  email: string;
  firstName: string;
  lastName: string;
  phone?: string;
  role?: string;
  department?: string;
  password: string;
  captchaToken?: string;
  captchaInput?: string;
}

export interface LoginApiPayload {
  email?: string;
  username?: string;
  password: string;
  captchaToken?: string;
  captchaInput?: string;
}

export interface AuthApiResponse {
  message?: string;
  id?: number;
  email?: string;
  username?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  role?: any;
  department?: string;
  verified?: boolean;
  twoFactorEnabled?: boolean;
  status?: any;
  error?: string;
}

class AuthApiService {
  private baseUrl: string;

  constructor() {
    this.baseUrl = API_BASE_URL;
  }

  private async request<T>(endpoint: string, options: RequestInit = {}): Promise<T> {
    const url = `${this.baseUrl}${endpoint.startsWith('/') ? '' : '/'}${endpoint}`;

    // const headers: Record<string, string> = {
    //   'Content-Type': 'application/json',
    //   'Accept': 'application/json',
    //   ...(options.headers as Record<string, string> || {}),
    // };

    const headers: Record<string, string> = {
      'Accept': 'application/json',
      ...(options.headers as Record<string, string> || {}),
    };

    if (options.body) {
      headers['Content-Type'] = 'application/json';
    }

    const config: RequestInit = {
      ...options,
      headers,
    };

    try {
      const response = await fetch(url, config);
      const data = await response.json().catch(() => ({}));

      if (!response.ok) {
        const errorMsg = data?.error || data?.message || `Request failed with status ${response.status}`;
        throw new Error(errorMsg);
      }

      return data as T;
    } catch (err: any) {
      // If direct fetch to backend failed (e.g. backend server down), format clean error
      if (err.message && !err.message.includes('fetch')) {
        throw err;
      }
      throw new Error(`Unable to connect to Java Spring Boot Backend at ${this.baseUrl}. Please verify the backend is running.`);
    }
  }

  /**
   * 1. GET /api/auth/captcha
   * Fetches visual CAPTCHA challenge generated by CaptchaService.java
   */
  public async getCaptcha(): Promise<CaptchaApiResponse> {
    return this.request<CaptchaApiResponse>('/api/auth/captcha', {
      method: 'GET',
    });
  }

  /**
   * 2. POST /api/auth/register
   * Registers user in MySQL database via UserService.java and dispatches Email OTP
   */
  public async register(payload: RegisterApiPayload): Promise<{ message: string; email: string; username: string }> {
    return this.request<{ message: string; email: string; username: string }>('/api/auth/register', {
      method: 'POST',
      body: JSON.stringify(payload),
    });
  }

  /**
   * 3. POST /api/auth/verify-otp
   * Verifies the 6-digit OTP code and activates user in MySQL
   */
  public async verifyOtp(email: string, otpCode: string, purpose: string = 'REGISTRATION'): Promise<{ message: string; email: string; status: string }> {
    return this.request<{ message: string; email: string; status: string }>('/api/auth/verify-otp', {
      method: 'POST',
      body: JSON.stringify({ email, otpCode, purpose }),
    });
  }

  /**
   * 4. POST /api/auth/resend-otp
   * Requests a fresh OTP dispatch to user email
   */
  public async resendOtp(email: string, purpose: string = 'REGISTRATION'): Promise<{ message: string }> {
    return this.request<{ message: string }>('/api/auth/resend-otp', {
      method: 'POST',
      body: JSON.stringify({ email, purpose }),
    });
  }

  /**
   * 5. POST /api/auth/login
   * Authenticates user credentials with BCrypt verification in Spring Boot
   */
  public async login(payload: LoginApiPayload): Promise<AuthApiResponse> {
    return this.request<AuthApiResponse>('/api/auth/login', {
      method: 'POST',
      body: JSON.stringify(payload),
    });
  }

  /**
   * 6. GET /api/auth/health
   * Checks Java Backend service status
   */
  public async checkHealth(): Promise<{ status: string; message: string; service: string }> {
    return this.request<{ status: string; message: string; service: string }>('/api/auth/health', {
      method: 'GET',
    });
  }
}

export const authApi = new AuthApiService();
